apiVersion: v1
kind: Secret
metadata:
  name: servicebus-msgqueue-auth
  labels:
    app: bindingconsumer
data:
  servicebus-msgqueue-connectionstring: "<your base64 encoded connection string of queue auth rule with manage rights>"
type: Opaque
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-servicebus
spec:
  secretTargetRef:
  - parameter: connection
    name: servicebus-msgqueue-auth
    key: servicebus-msgqueue-connectionstring
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: bindingconsumer-scaler
  labels:
    app: bindingconsumer
    deploymentName: consumer
spec:
  scaleTargetRef:
    deploymentName: consumer
    minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: msgqueue
      queueLength: '5'
    authenticationRef:
      name: trigger-auth-servicebus